# traefik.yml
api:
  dashboard: true  # Enable the Traefik dashboard
  insecure: false  # Disable insecure access to the dashboard

# Logging Configuration
log:
  level: INFO  # Options: DEBUG, INFO, WARN, ERROR, FATAL

# EntryPoints Configuration
entryPoints:
  web:
    address: ":80"  # Listen on port 80 for HTTP
    http:
      redirections:
        entryPoint:
          to: websecure  # Redirect HTTP to HTTPS
          scheme: https

  websecure:
    address: ":443"  # Listen on port 443 for HTTPS
    http:
      tls:
        certResolver: letsencrypt  # Use Let's Encrypt for SSL certificates

# Providers Configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"  # Connect to Docker socket
    exposedByDefault: false  # Only expose containers with explicit labels
    network: web  # Use the Docker network named "web"

# Certificates Resolvers Configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: your@mail.com  # Replace with your email
      storage: /acme.json  # File to store SSL certificates
      httpChallenge:
        entryPoint: web  # Use the "web" entry point for HTTP challenges
