version: '3.8'

services:
  odoo:
    image: odoo:latest
    container_name: odoo
    restart: unless-stopped
    env_file: .env
    user: "odoo:odoo" 
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo  # Named volume for Odoo filestore
      - ./odoo-config/odoo.conf:/etc/odoo/odoo.conf    # Named file for Odoo configuration
      - odoo-custom-modules:/mnt/extra-addons  # Mount custom modules directory
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo.rule=Host(`terrabloque.com`)"
      - "traefik.http.routers.odoo.entrypoints=websecure"
      - "traefik.http.routers.odoo.tls.certresolver=letsencrypt"
      #Configuración para pagos online
      - "traefik.http.middlewares.odoo-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.odoo-headers.headers.customrequestheaders.X-Forwarded-For=$$remote_addr"
      - "traefik.http.middlewares.odoo-headers.headers.customrequestheaders.X-Forwarded-Host=$$http_host"
      
      # Aplica el middleware a tu router de Odoo
      - "traefik.http.routers.odoo.middlewares=odoo-headers"

  db:
    image: postgres:13
    container_name: odoo-db
    restart: unless-stopped
    env_file: .env
    user: "999:1991"  # Runs the container as UID 999, GID 1991
    volumes:
      - postgresql-data:/var/lib/postgresql/data  # Named volume for PostgreSQL database
    networks:
      - web

networks:
  web:
    external: true

volumes:
  odoo-data:
  postgresql-data:
  odoo-config:
  odoo-custom-modules:

