version: '3.8'

services:
  odoo:
    image: odoo:latest
    container_name: odoo
    restart: unless-stopped
    env_file: .env
    user: "odoo:odoo" 
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo  # Named volume for Odoo filestore
      - ./odoo-config/odoo.conf:/etc/odoo/odoo.conf    # Named file for Odoo configuration
      - odoo-custom-modules:/mnt/extra-addons  # Mount custom modules directory
    networks:
      - web
    labels:
      - "traefik.enable=true"

  # --- Definici贸n del Servicio de destino ---
      - "traefik.http.services.odoo-service.loadbalancer.server.port=8069"

  # --- Definici贸n del Middleware 
      - "traefik.http.middlewares.odoo-https-redirect.headers.customrequestheaders.X-Forwarded-Proto=https"

  # --- Router para terrabloque.com ---
      - "traefik.http.routers.odoo-terrabloque.rule=Host(`terrabloque.com`)"
      - "traefik.http.routers.odoo-terrabloque.entrypoints=websecure"
      - "traefik.http.routers.odoo-terrabloque.tls.certresolver=letsencrypt"
      - "traefik.http.routers.odoo-terrabloque.service=odoo-service" # <--- Le dice a d贸nde ir
      - "traefik.http.routers.odoo-terrabloque.middlewares=odoo-https-redirect" # <--- Le aplica el middleware

  # --- Router para madebloque.com ---
      - "traefik.http.routers.odoo-madebloque.rule=Host(`madebloque.com`)"
      - "traefik.http.routers.odoo-madebloque.entrypoints=websecure"
      - "traefik.http.routers.odoo-madebloque.tls.certresolver=letsencrypt"
      - "traefik.http.routers.odoo-madebloque.service=odoo-service" # <--- Le dice a d贸nde ir
      - "traefik.http.routers.odoo-madebloque.middlewares=odoo-https-redirect" 

  # --- Router para supertirivita.terrabloque.com ---
      - "traefik.http.routers.odoo-supertirivita.rule=Host(`supertirivita.terrabloque.com`)"
      - "traefik.http.routers.odoo-supertirivita.entrypoints=websecure"
      - "traefik.http.routers.odoo-supertirivita.tls.certresolver=letsencrypt"
      - "traefik.http.routers.odoo-supertirivita.service=odoo-service" 
      - "traefik.http.routers.odoo-supertirivita.middlewares=odoo-https-redirect" 

  # --- Router para tejibsa.com ---
      - "traefik.http.routers.odoo-tejibsa.rule=Host(`tejibsa.com`)"
      - "traefik.http.routers.odoo-tejibsa.entrypoints=websecure"
      - "traefik.http.routers.odoo-tejibsa.tls.certresolver=letsencrypt"
      - "traefik.http.routers.odoo-tejibsa.service=odoo-service" 
      - "traefik.http.routers.odoo-tejibsa.middlewares=odoo-https-redirect" 

  # --- Router para albor.terrabloque.com ---
      - "traefik.http.routers.odoo-albor.rule=Host(`albor.terrabloque.com`)"
      - "traefik.http.routers.odoo-albor.entrypoints=websecure"
      - "traefik.http.routers.odoo-albor.tls.certresolver=letsencrypt"
      - "traefik.http.routers.odoo-albor.service=odoo-service" 
      - "traefik.http.routers.odoo-albor.middlewares=odoo-https-redirect" 
  db:
    image: postgres:13
    container_name: odoo-db
    restart: unless-stopped
    env_file: .env
    user: "999:1991"  # Runs the container as UID 999, GID 1991
    volumes:
      - postgresql-data:/var/lib/postgresql/data  # Named volume for PostgreSQL database
    networks:
      - web

networks:
  web:
    external: true

volumes:
  odoo-data:
  postgresql-data:
  odoo-config:
  odoo-custom-modules:

